import image from '@/assets/hipfest3.jpg'

export const events = [
  {
    id: 'breaking-event',
    name: 'Breaking World Cup',
    category: 'breaking',
    startDate: '2025-01-01',
    endDate: '2025-01-02',
    startTime: '10:00',
    endTime: '18:00',
    location: 'Sân vận động Thống Nhất',
    image: image.src,
  },
  {
    id: 'all-style-event',
    name: 'All-Style Hip-Hop Battle',
    category: 'all_style',
    startDate: '2025-01-03',
    endDate: '2025-01-03',
    startTime: '14:00',
    endTime: '20:00 PM',
    location: 'Sân AM vận động Thống Nhất',
    image: image.src,
  },
  {
    id: 'beatbox-event',
    name: 'Beatbox Battle Championship',
    category: 'beatbox',
    startDate: '2025-01-04',
    endDate: '2025-01-04',
    startTime: '16:00',
    endTime: '22:00',
    location: 'Sân vận động Thống Nhất',
    image: image.src,
  },
  {
    id: 'freestyle-rap-event',
    name: 'Freestyle Rap Battle',
    category: 'freestyle_rap',
    startDate: '2025-01-05',
    endDate: '2025-01-05',
    startTime: '19:00',
    endTime: '23:00',
    location: 'Sân vận động Thống Nhất',
    image: image.src,
  },
  {
    id: 'graffiti-event',
    name: 'Graffiti Live Art Jam',
    category: 'graffiti',
    startDate: '2025-01-06',
    endDate: '2025-01-06',
    startTime: '12:00',
    endTime: '18:00',
    location: 'Sân vận động Thống Nhất',
    image: image.src,
  },
  {
    id: 'dj-event',
    name: 'DJ Battle Showdown',
    category: 'dj',
    startDate: '2025-01-07',
    endDate: '2025-01-08',
    startTime: '20:00',
    endTime: '02:00',
    location: 'Sân vận động Thống Nhất',
    image: image.src,
  },
]
